const workoutpresets = [
  {
    name: 'Flying 40 Intervals',
    tasks: [
      {key: 1, task: 'Warm up', intensity: 25, duration: (15 * 60)},
      {key: 2, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 3, task: 'Recover', intensity: 25, duration: 20},
      {key: 4, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 5, task: 'Recover', intensity: 25, duration: 20},
      {key: 6, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 7, task: 'Recover', intensity: 25, duration: 20},
      {key: 8, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 9, task: 'Recover', intensity: 25, duration: 20},
      {key: 10, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 11, task: 'Recover', intensity: 25, duration: 20},
      {key: 12, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 13, task: 'Recover', intensity: 25, duration: 20},
      {key: 14, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 15, task: 'Recover', intensity: 25, duration: 20},
      {key: 16, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 17, task: 'Recover', intensity: 25, duration: 20},
      {key: 18, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 19, task: 'Recover', intensity: 25, duration: 20},
      {key: 20, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 21, task: 'Recover', intensity: 25, duration: 20},
      {key: 22, task: 'Pedal Easy', intensity: 10, duration: (5 * 60)},
      {key: 23, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 24, task: 'Recover', intensity: 25, duration: 20},
      {key: 25, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 26, task: 'Recover', intensity: 25, duration: 20},
      {key: 27, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 28, task: 'Recover', intensity: 25, duration: 20},
      {key: 29, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 30, task: 'Recover', intensity: 25, duration: 20},
      {key: 31, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 32, task: 'Recover', intensity: 25, duration: 20},
      {key: 33, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 34, task: 'Recover', intensity: 25, duration: 20},
      {key: 35, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 36, task: 'Recover', intensity: 25, duration: 20},
      {key: 37, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 38, task: 'Recover', intensity: 25, duration: 20},
      {key: 39, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 40, task: 'Recover', intensity: 25, duration: 20},
      {key: 41, task: 'Pedal Hard', intensity: 85, duration: 40},
      {key: 42, task: 'Recover', intensity: 25, duration: 20},
      {key: 43, task: 'Cool Down', intensity: 10, duration: (10 * 60)}
    ]
  },
  {
    name: 'Descending Interval Set',
    tasks: [
      {key: 44, task: 'Warm up', intensity: 25, duration: (10 * 60)},
      {key: 45, task: 'All-out fast', intensity: 95, duration: 45},
      {key: 46, task: 'Easy', intensity: 15, duration: 255},
      {key: 47, task: 'All-out fast', intensity: 95, duration: 40},
      {key: 48, task: 'Easy', intensity: 15, duration: 260},
      {key: 49, task: 'All-out fast', intensity: 95, duration: 35},
      {key: 50, task: 'Easy', intensity: 15, duration: 265},
      {key: 51, task: 'All-out fast', intensity: 95, duration: 30},
      {key: 52, task: 'Easy', intensity: 15, duration: 270},
      {key: 53, task: 'All-out fast', intensity: 95, duration: 25},
      {key: 54, task: 'Easy', intensity: 15, duration: 275},
      {key: 55, task: 'All-out fast', intensity: 95, duration: 20},
      {key: 56, task: 'Easy', intensity: 15, duration: 280},
      {key: 57, task: 'All-out fast', intensity: 95, duration: 15},
      {key: 58, task: 'Easy', intensity: 15, duration: 285},
      {key: 59, task: 'Cool down', intensity: 10, duration: 5 * 60}
    ]
  }
]

export default workoutpresets